language: python
python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
  - "3.4"
#  - "pypy"
#  - "pypy3"
os:
  - linux
#  - osx
# command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install -r test_requirements.txt"
# command to run tests
script: nosetests --with-coverage --cover-package=pymal
after_success:
  - coveralls
